config/routes.rb
GmailClone::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resources :emails, :only => [:create, :new, :index]
  resource :session, :only => [:create, :destroy, :new]

  root :to => "emails#index"
end

app/models/email.rb
class Email < ActiveRecord::Base
  attr_accessible :author, :subject, :body, :user_id, :recipients, :email_recipient_tags
  
  validates :author, presence: true
  
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  
  has_many(
    :email_recipient_tags,
    class_name: "EmailRecipient",
    foreign_key: :email_id,
    primary_key: :id
  )
  
  has_many :recipients, :through => :email_recipient_tags, source: :recipient
  
end

app/models/email_recipient.rb
class EmailRecipient < ActiveRecord::Base
  attr_accessible :recipient, :email, :email_id, :user_id
  #validates :recipient, :email, presence: true

  belongs_to(
  :recipient,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )
  
  belongs_to(
  :email,
  class_name: "Email",
  foreign_key: :email_id,
  primary_key: :id
  )
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :id
  attr_reader :password

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token
  
  has_many(
  :authored_emails,
  class_name: "Email",
  foreign_key: :user_id,
  primary_key: :id
  )
  
  has_many(
  :emailed_recipient_tags,
  class_name: "EmailRecipient",
  foreign_key: :user_id,
  primary_key: :id
  )
  
  has_many :received_emails, :through => :emailed_recipient_tags, source: :email

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_filter :require_current_user!
  
  def new
    
  end
  
  def create
    # subject = params[:email][:subject]
    #     params[:email][:body]
    # May have to parse out parameters and set the "recipients" to the proper users
    @email = Email.new(subject: params[:email][:subject], body: params[:email][:body])
    if @email.save
      render :json => @email
    else
      render :json => @email.errors, :status => 422
    end
  end
  
  def index
    @authored_emails = current_user.authored_emails
    @received_emails = current_user.received_emails
    puts "-------------"
    puts Email.all
    puts "-------------"
    respond_to do |format|
      format.html { render :index }
      format.html { render :json => { authored_emails: @authored_emails, received_emails: @received_emails } }
    end  
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to root_url
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to root_url
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end
  
  def index
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GmailClone - Version AC</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<div id="content">
</div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>